#ifndef ROBOCUP_WEIGHT_DROPOFF_H
#define ROBOCUP_WEIGHT_DROPOFF_H

typedef enum
{
    DROPOFF_STATUS_IDLE,
    DROPOFF_STATUS_ALIGN,
    DROPOFF_STATUS_REVERSE,
    DROPOFF_STATUS_SETTLE,
    DROPOFF_STATUS_LOWER,
    DROPOFF_STATUS_UNLOAD,
    DROPOFF_STATUS_DONE
} weight_dropoff_state_t;

void weight_dropoff_state_update();
#endif
