//
// Created by Joe Elder on 14/09/2026
//

#ifndef ROBOCUP_WEIGHT_PICKUP_H
#define ROBOCUP_WEIGHT_PICKUP_H


typedef enum {
  PICKUP_STATUS_IDLE,
  PICKUP_STATUS_ALIGNING,
  PICKUP_STATUS_CHECKING_WEIGHT_TYPE,
  PICKUP_STATUS_FAKE_WEIGHT_DETECTED,
  PICKUP_STATUS_FAKE_WEIGHT_LIFTING,
  PICKUP_STATUS_FAKE_WEIGHT_MOVING,
  PICKUP_STATUS_REAL_WEIGHT_DETECTED,
  PICKUP_STATUS_LOADING_WEIGHT,
  PICKUP_STATUS_LIFTING_WEIGHT,
  PICKUP_STATUS_LOWERING_RAILS,
  PICKUP_STATUS_FAKE_WEIGHT_CLEAR_DELAY,
  PICKUP_STATUS_LOADING_WEIGHT_CONFIRM_DELAY,
  PICKUP_STATUS_WEIGHT_LOST
} weight_pickup_state_t;

void weight_pickup_state_update();

weight_pickup_state_t weight_pickup_get_state(void);

#endif // ROBOCUP_WEIGHT_PICKUP_H
